global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#aleksandr_kartavykh'
