kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: UiTZH1LdbYNDZFC9LRlU6Lzg99fHKXrKiWArm+v4vRo=
      - identity: {}
